version: '3.8'
services:
  frontend:
    build: ./docker/frontend
    volumes:
      - ./frontend:/var/www/frontend
  backend:
    build: ./docker/backend
    volumes:
      - ./backend:/var/www/backend
  nginx:
    image: nginx 
    ports:
      - 80:80 
    volumes:
      - ./frontend:/var/www/frontend
      - ./backend:/var/www/backend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - app-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    environment:
        MYSQL_USERNAME: ${DB_USERNAME}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        PMA_HOST: ${DB_HOST}
volumes:
  app-data:
